spring:
  application:
    name: IdmService
  datasource:
    url: jdbc:mysql://database:3306
    username: root
    password: DnJAws!17

server:
  address: 0.0.0.0
  port: 8081
  error:
    include-exception: true
    include-message: always

logging:
  file:
    name: ./IdmService.log

idm:
  # (joe.delnano) I tried updating this field to be the path in the container, but it didn't seem to work on a first pass try
  key-file-name: ec-key.json
  access-token-expire: 30m
  refresh-token-expire: 12h
  max-refresh-token-life-time: 30d
