spring:
  application:
    name: IdmService
  datasource:
    url: jdbc:mysql://database:3306
    username: root #CHANGE THESE FIELDS AFTER DEBUG
    password: DnJAws!17

idm:
  key-file-name: ec-key.json
  access-token-expire: 2s
  refresh-token-expire: 5s
  max-refresh-token-life-time: 10s
